### ISSUE TITLE
unknown dependencies

### ISSUE THREAD

**Issue by DanHolli** [NovaViper/TetraCraft#1]
TetraCraft craft is missing some of it's dependencies. Install the dependencies or uninstall TetraCraft.
that is the the message I got from Forge when starting minecraft

**Comment by NovaViper** [comment]
You need Cryogenic Library, the mod depends on the library mod I created. You can download it [here](http://minecraft.curseforge.com/projects/cryogenic-library)

**Comment by DanHolli** [comment]
you should add the dependency line with the modid of Cryogenic

**Comment by NovaViper** [comment]
I did, not sure why Forge didn't say the dependency. If I didn't, it would have just crashed with an error saying 'Missing methods or Methods does not exist'

**Comment by DanHolli** [comment]
odd...

**Comment by DanHolli** [comment]
I noticed in the mcmod.info of 1.10.2 the dependency line is empty

**Comment by NovaViper** [comment]
I have the dependency internally built into the code, thats even why it said check for the dependency. It's [here](https://github.com/NovaViper/TetraCraft/blob/1.9.4/src/main/java/com/novaviper/tetracraft/lib/ModReference.java)

**Comment by DanHolli** [comment]
I was using 1.10.2

**Comment by NovaViper** [comment]
I know but the files for 1.9.4 and 1.10.2 are the same file since it works with both versions seamlessly

**Comment by DanHolli** [comment]
the 1.10.2 branch doesn't have the library source in it

**Comment by NovaViper** [comment]
Library source? Neither branches doesn't have the source of the library mod. I'm not sure what you mean

**Comment by NovaViper** [comment]
But, to fix your issue, download Cryogenic Library and place it in the same file folder as TeraCraft is in. The file that is uploaded on both projects are seamlessly compatible with 1.9.4 and 1.10.2. The sources for both branched are the same except for renaming the versions.

**Comment by DanHolli** [comment]
I already added the library and it worked you may close this if you want... or not, I'm fine either way

**Comment by NovaViper** [comment]
Oh ok
